### ISSUE TITLE
cross compilation to use on Qnap NAS - configure stuck on error

### ISSUE THREAD

**Issue by nephaste** [fernando-rodriguez/avmount#4]
Hi Thanks for this project, i planned to build it on qnap NAS but on configure i am stuck on this error

`checking if x86_64-QNAP_FW43-linux-gnu-gcc supports -fno-rtti -fno-exceptions... no
checking for x86_64-QNAP_FW43-linux-gnu-gcc option to produce PIC... -fPIC -DPIC
checking if x86_64-QNAP_FW43-linux-gnu-gcc PIC flag -fPIC -DPIC works... yes
checking if x86_64-QNAP_FW43-linux-gnu-gcc static flag -static works... yes
checking if x86_64-QNAP_FW43-linux-gnu-gcc supports -c -o file.o... yes
checking if x86_64-QNAP_FW43-linux-gnu-gcc supports -c -o file.o... (cached) yes
checking whether the x86_64-QNAP_FW43-linux-gnu-gcc linker (/data/x-tools/x86_64-QNAP_FW43-linux-gnu/x86_64-QNAP_FW43-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking whether make sets $(MAKE)... (cached) yes
checking whether ln -s works... yes
checking for perl... /usr/bin/perl
checking for git... /usr/bin/git
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for ANSI C header files... (cached) yes
checking for inttypes.h... (cached) yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for setxattr... yes
checking for mktime... yes
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for open_memstream... yes
checking for x86_64-QNAP_FW43-linux-gnu-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for TALLOC... yes
./configure: line 13495: AX_LIB_READLINE: command not found
./configure: line 14556: syntax error near unexpected token `,AC_MSG_ERROR'
./configure: line 14556: `AX_PTHREAD(,AC_MSG_ERROR([POSIX threads are required to build this program]))'
`
any idea... all libs are well compiled in my prefix 

`PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"  CFLAGS="-O2 -I$PREFIX/include " CXXFLAGS="-O2 -I$PREFIX/include"     LDFLAGS="-L$PREFIX/lib -Wl,-rpath,$PREFIX/lib" CPPFLAGS="-O2 -I$PREFIX/include"     ./configure --prefix=$PREFIX --host=${HOST} --bindir=$PREFIX/bin --sbindir=$PREFIX/bin --libexecdir=$PREFIX/libexec --libdir=$PREFIX/lib --datadir=$PREFIX/share --datarootdir=$PREFIX/share --sysconfdir=$PREFIX/etc --sharedstatedir=$PREFIX/com --localstatedir=$PREFIX/var --includedir=$PREFIX/include --oldincludedir=$PREFIX/include --infodir=$PREFIX/share/info --localedir=$PREFIX/share/locale PKG_CONFIG_LIBDIR=$PREFIX/lib TALLOC_CFLAGS="-O2 -I$PREFIX/include " TALLOC_LIBS="-L$PREFIX/lib"`

thanks for your help

autoconf version 2.69
pkg-config 0.26

**Comment by fdev1** [comment]
Please try the staging branch. I believe those where fixed recently. They will be on the next release when I get the chance to do it.

**Comment by nephaste** [comment]
Thanks Fernando.. i tried but .. still have issue (FYI my host is an Ubuntu 1404)

> /SRC/avmount-staging# ./autogen.sh
> * Runing libtoolize...
> * Running aclocal...
> gl/m4/va_copy.m4:62: warning: underquoted definition of AC_CHECK_VA_COPY
> gl/m4/va_copy.m4:62:   run info Automake 'Extending aclocal'
> gl/m4/va_copy.m4:62:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
> * Runing autoconf...
> * Running autoheader...
> * Running automake...
> configure.ac:66: installing '../compile'
> configure.ac:203: error: required file '../config.rpath' not found
> configure.ac:19: installing '../missing'
> BUG.am: error: 'install.sh' is an anachronism; use 'install-sh' instead
> Makefile.am: installing './INSTALL'
> src/Makefile.am: installing '../depcomp'

once configure done

> ...
> checking for memmove... yes
> checking for intptr_t... yes
> checking for uintptr_t... yes
> checking for ptrdiff_t... yes
> checking for useconds_t... yes
> checking for bool... yes
> checking for TALLOC... yes
> checking for a readline compatible library... no
> checking whether x86_64-QNAP_FW43-linux-gnu-gcc is Clang... no
> checking whether pthreads work with -pthread... yes
> checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
> checking whether more special flags are required for pthreads... no
> checking for PTHREAD_PRIO_INHERIT... yes
> checking for FUSE... yes
> checking for LIBUPNP... yes
> checking whether Upnp_Event_Subscribe.PublisherUrl is char*... yes
> checking whether Upnp_Action_Complete.CtrlUrl is char*... yes
> checking whether Upnp_State_Var_Complete.CtrlUrl is char*... yes
> checking for SetLogFileNames in -lupnp... no
> checking for curl-config... /usr/local/bin/curl-config
> checking for curl (7.50.3) >= 7.45.0... yes
> checking for malloc_trim... yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: error: cannot find input file: `Makefile.in'
> 

look like an issue with the Makefile.in .. fixable ?

**Comment by fdev1** [comment]
Automake is failing. I believe that is a bug with autotools (or with the AM_ICONV macro). Try:

`# touch config.rpath`
`# ./autogen.sh`

Then run configure again. If it works please report back and I'll add an empty config.rpath as a workaround.

**Comment by fdev1** [comment]
Also make sure to start with a clean tree. If you have an install.sh on your project root delete it first. `git clean -f` should do it.

**Comment by nephaste** [comment]
> root@steph-virtual-machine:/SRC/avmount-staging# touch config.rpath
> root@steph-virtual-machine:/SRC/avmount-staging# ./autogen.sh
> * Runing libtoolize...
> * Running aclocal...
> gl/m4/va_copy.m4:62: warning: underquoted definition of AC_CHECK_VA_COPY
> gl/m4/va_copy.m4:62:   run info Automake 'Extending aclocal'
> gl/m4/va_copy.m4:62:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
> * Runing autoconf...
> * Running autoheader...
> * Running automake...
> configure.ac:66: installing '../compile'
> configure.ac:19: installing '../missing'
> BUG.am: error: 'install.sh' is an anachronism; use 'install-sh' instead
> Makefile.am: installing './INSTALL'
> src/Makefile.am: installing '../depcomp'
> 


> ...
> checking for open_memstream... yes
> checking limits.h usability... yes
> checking limits.h presence... yes
> checking for limits.h... yes
> checking for strerror... yes
> checking for usleep... yes
> checking for strnlen... yes
> checking for memmove... yes
> checking for intptr_t... yes
> checking for uintptr_t... yes
> checking for ptrdiff_t... yes
> checking for useconds_t... yes
> checking for bool... yes
> checking for TALLOC... yes
> checking for a readline compatible library... no
> checking whether x86_64-QNAP_FW43-linux-gnu-gcc is Clang... no
> checking whether pthreads work with -pthread... yes
> checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
> checking whether more special flags are required for pthreads... no
> checking for PTHREAD_PRIO_INHERIT... yes
> checking for FUSE... yes
> checking for LIBUPNP... yes
> checking whether Upnp_Event_Subscribe.PublisherUrl is char*... yes
> checking whether Upnp_Action_Complete.CtrlUrl is char*... yes
> checking whether Upnp_State_Var_Complete.CtrlUrl is char*... yes
> checking for SetLogFileNames in -lupnp... no
> checking for curl-config... /usr/local/bin/curl-config
> checking for curl (7.50.3) >= 7.45.0... yes
> checking for malloc_trim... yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: error: cannot find input file: `Makefile.in'

same effect :(

config.log output :

https://pastebin.com/qkbH5LwL

can it be link to ncurses not cross compiled in my prefix path ? (ses some errors in config.log)

I dont see it in the required dependencies ( ./configure --help)

**Comment by nephaste** [comment]
just tried to add ncurses to my path.. no change

**Comment by fdev1** [comment]
Can you confirm that you're working with a clean tree and that there is no file named install.sh or install-sh in your project root before running ./autogen.sh? You fixed the first error but automake is still failing with `BUG.am: error: 'install.sh' is an anachronism; use 'install-sh' instead`. That could happen if you have a file named install.sh in your project directory. Automake doesn't like that. If you created that file on purpose try naming it something else, like myinstall.sh.

**Comment by nephaste** [comment]
Hi Fernando

no such file.. also tried download directly from Githug from staging tree the zipped file


> root@steph-virtual-machine:/SRC/avmount-staging# ls -alh
> total 968K
> drwxrwxr-x+    5 root  root  4,0K avril  2 10:58 .
> drwxrwx---+ 1327 steph users  52K avril  2 10:58 ..
> -rw-rw----+    1 root  root   42K avril  2 10:58 aclocal.m4
> -rwxrwxr-x+    1 root  root   278 mars  22 04:10 AUTHORS
> -rwxrwxr-x+    1 root  root   312 mars  22 04:10 autogen.sh
> drwxr-x---+    2 root  root  4,0K avril  2 10:58 autom4te.cache
> -rwxrwxr-x+    1 root  root   17K mars  22 04:10 ChangeLog
> -rw-rw----+    1 root  root  6,5K avril  2 12:33 config.h.in
> -rw-rw----+    1 root  root   80K avril  2 10:55 config.log
> -rwxrwxr-x+    1 root  root    21 avril  2 10:59 config.rpath
> -rwxrwx--x+    1 root  root   63K avril  2 10:55 config.status
> -rwxrwx---+    1 root  root  539K avril  2 10:58 configure
> -rwxrwxr-x+    1 root  root   11K mars  22 04:10 configure.ac
> -rwxrwxr-x+    1 root  root   18K mars  22 04:10 COPYING
> -rwxrwxr-x+    1 root  root   291 mars  22 04:10 .gitignore
> drwxrwxr-x+    3 root  root  4,0K avril  2 10:24 gl
> -rw-r-----+    1 root  root   16K avril  2 10:58 INSTALL
> -rwxrwxr-x+    1 root  root  1,1K mars  22 04:10 Makefile.am
> -rwxrwxr-x+    1 root  root  1015 mars  22 04:10 makepkg.sh
> -rwxrwxr-x+    1 root  root  7,6K mars  22 04:10 NEWS
> -rwxrwxr-x+    1 root  root   13K mars  22 04:10 README
> -rwxrwxr-x+    1 root  root   13K mars  22 04:10 search_help.txt
> drwxrwxr-x+    3 root  root  4,0K avril  2 10:24 src
> -rwxrwxr-x+    1 root  root  1,1K mars  22 04:10 THANKS
> -rwxrwxr-x+    1 root  root  1,5K mars  22 04:10 TODO


find /SRC/avmount-staging -name install.sh

 report nothing

**Comment by nephaste** [comment]
new try

> root@steph-virtual-machine:/SRC# git clone -b staging https://github.com/avbox/avmount.git
> Cloning into 'avmount'...
> remote: Counting objects: 886, done.
> remote: Compressing objects: 100% (3/3), done.
> remote: Total 886 (delta 0), reused 0 (delta 0), pack-reused 883
> Receiving objects: 100% (886/886), 1.31 MiB | 363.00 KiB/s, done.
> Resolving deltas: 100% (531/531), done.
> Checking connectivity... done.
> 
> root@steph-virtual-machine:/SRC# cd avmount
> 
> root@steph-virtual-machine:/SRC/avmount# git clean -f
> root@steph-virtual-machine:/SRC/avmount# touch config.rpath
> root@steph-virtual-machine:/SRC/avmount# ./autogen.sh
> * Runing libtoolize...
> * Running aclocal...
> gl/m4/va_copy.m4:62: warning: underquoted definition of AC_CHECK_VA_COPY
> gl/m4/va_copy.m4:62:   run info Automake 'Extending aclocal'
> gl/m4/va_copy.m4:62:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
> * Runing autoconf...
> * Running autoheader...
> * Running automake...
> configure.ac:66: installing '../compile'
> configure.ac:19: installing '../missing'
> BUG.am: error: 'install.sh' is an anachronism; use 'install-sh' instead
> Makefile.am: installing './INSTALL'
> src/Makefile.am: installing '../depcomp'

> ....
> checking whether readline supports history... yes
> checking history.h usability... no
> checking history.h presence... no
> checking for history.h... no
> checking readline/history.h usability... yes
> checking readline/history.h presence... yes
> checking for readline/history.h... yes
> checking whether x86_64-QNAP_FW43-linux-gnu-gcc is Clang... no
> checking whether pthreads work with -pthread... yes
> checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
> checking whether more special flags are required for pthreads... no
> checking for PTHREAD_PRIO_INHERIT... yes
> checking for FUSE... yes
> checking for LIBUPNP... yes
> checking whether Upnp_Event_Subscribe.PublisherUrl is char*... yes
> checking whether Upnp_Action_Complete.CtrlUrl is char*... yes
> checking whether Upnp_State_Var_Complete.CtrlUrl is char*... yes
> checking for SetLogFileNames in -lupnp... no
> checking for curl-config... /usr/local/bin/curl-config
> checking for curl (7.50.3) >= 7.45.0... yes
> checking for malloc_trim... yes
> checking git commit hash... b9864157476116b2106fc37aaa83ef996ea3e0e8
> checking git branch... staging
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: error: cannot find input file: `Makefile.in'

**Comment by nephaste** [comment]
Ok i found... this damned files was in my parent directory in /SRC was searching in /SRC/avmount

all is compiling now...

> ...
> 
> /bin/bash ../libtool  --tag=CC   --mode=link x86_64-QNAP_FW43-linux-gnu-gcc -I../gl -I/opt/AVMount/include   -pthread -I/opt/AVMount/include/upnp   -D_FILE_OFFSET_BITS=64 -I/opt/AVMount/include/fuse   -std=gnu99  -O2 -I/opt/AVMount/include -I/opt/AVMount/include/ncurses  -Os -Wall -I/opt/AVMount/include   -pthread -D_FILE_OFFSET_BITS=64 -I/opt/AVMount/include/fuse   -DFUSE_USE_VERSION=22 -pthread -I/opt/AVMount/include/upnp    -L/opt/AVMount/lib -Wl,-rpath,/opt/AVMount/lib -Wl,-rpath,/opt/AVMount/lib -L/opt/AVMount/lib -ltalloc   -pthread -L/opt/AVMount/lib -lfuse   -pthread -L/opt/AVMount/lib -lupnp -lthreadutil -lixml   -lcurl -o test_upnp log.o object.o service.o device.o device_list.o didl_object.o media_file.o file_buffer.o content_dir.o vfs.o djfs.o upnp_util.o string_util.o xml_util.o ptr_array.o talloc_util.o cache.o clientmgr.o stream.o fuse_fs.o iface_util.o    test_upnp.o -L../gl -lgnu -Wl,-rpath,/opt/AVMount/lib -L/opt/AVMount/lib -ltalloc   -pthread -L/opt/AVMount/lib -lupnp -lthreadutil -lixml   -pthread -L/opt/AVMount/lib -lfuse     -lreadline -lncurses
> libtool: link: x86_64-QNAP_FW43-linux-gnu-gcc -I../gl -I/opt/AVMount/include -pthread -I/opt/AVMount/include/upnp -D_FILE_OFFSET_BITS=64 -I/opt/AVMount/include/fuse -std=gnu99 -O2 -I/opt/AVMount/include -I/opt/AVMount/include/ncurses -Os -Wall -I/opt/AVMount/include -pthread -D_FILE_OFFSET_BITS=64 -I/opt/AVMount/include/fuse -DFUSE_USE_VERSION=22 -pthread -I/opt/AVMount/include/upnp -Wl,-rpath -Wl,/opt/AVMount/lib -Wl,-rpath -Wl,/opt/AVMount/lib -pthread -pthread -o test_upnp log.o object.o service.o device.o device_list.o didl_object.o media_file.o file_buffer.o content_dir.o vfs.o djfs.o upnp_util.o string_util.o xml_util.o ptr_array.o talloc_util.o cache.o clientmgr.o stream.o fuse_fs.o iface_util.o test_upnp.o -Wl,-rpath -Wl,/opt/AVMount/lib -pthread -pthread  -L/opt/AVMount/lib -L../gl /SRC/avmount/gl/.libs/libgnu.a /opt/AVMount/lib/libcurl.so -lssl -lcrypto -lz -ltalloc /opt/AVMount/lib/libupnp.so /opt/AVMount/lib/libthreadutil.so /opt/AVMount/lib/libixml.so /opt/AVMount/lib/libfuse.so -ldl /opt/AVMount/lib/libiconv.so -lreadline -lncurses -pthread -Wl,-rpath -Wl,/opt/AVMount/lib -Wl,-rpath -Wl,/opt/AVMount/lib
> make[3]: Leaving directory `/SRC/avmount/src'
> make[2]: Leaving directory `/SRC/avmount/src'
> make[2]: Entering directory `/SRC/avmount'
> cd . && /bin/bash ./config.status config.h
> config.status: creating config.h
> config.status: config.h is unchanged
> make[2]: Leaving directory `/SRC/avmount'
> make[1]: Leaving directory `/SRC/avmount'
> root@steph-virtual-machine:/SRC/avmount# make install
> make  -C src install
> make[1]: Entering directory `/SRC/avmount/src'
> make  install-am
> make[2]: Entering directory `/SRC/avmount/src'
> make[3]: Entering directory `/SRC/avmount/src'
>  /bin/mkdir -p '/opt/AVMount/bin'
>   /bin/bash ../libtool   --mode=install /usr/bin/install -c avmount '/opt/AVMount/bin'
> libtool: install: /usr/bin/install -c avmount /opt/AVMount/bin/avmount
> make  install-exec-hook
> make[4]: Entering directory `/SRC/avmount/src'
> make[4]: Nothing to be done for `install-exec-hook'.
> make[4]: Leaving directory `/SRC/avmount/src'
> make[3]: Nothing to be done for `install-data-am'.
> make[3]: Leaving directory `/SRC/avmount/src'
> make[2]: Leaving directory `/SRC/avmount/src'
> make[1]: Leaving directory `/SRC/avmount/src'

dont know why i had this file in this directory...
